# Generated by Django 5.1 on 2024-08-13 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='payment_terms',
            field=models.TextField(default=0),
        ),
        migrations.AddField(
            model_name='service',
            name='service_image',
            field=models.ImageField(blank=True, null=True, upload_to='service_images/'),
        ),
        migrations.AddField(
            model_name='service',
            name='service_package',
            field=models.CharField(default=0, max_length=255),
        ),
        migrations.AddField(
            model_name='service',
            name='service_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='service',
            name='service_tax',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
